package test;

import structure.Expression;
import structure.logic.*;

import java.util.ArrayList;

/**
 * Created with IntelliJ IDEA.
 * User: Xottab
 * Date: 18.11.13
 * Time: 17:21
 * To change this template use File | Settings | File Templates.
 */
public enum ContrapositionRule {

    R_1(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1"))))),
    R_2(new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1")))), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1"))))))),
    R_3(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1")))))),
    R_4(new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1")))), new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1"))))))),
    R_5(new Entailment(new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1")))), new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1")))))), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1")))), new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1"))))))))),
    R_6(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1")))), new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1")))))))),
    R_7(new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1"))))), new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1")))), new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1"))))))), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1"))))))))),
    R_8(new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1")))), new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1"))))))), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1")))))))),
    R_9(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1"))))))),
    R_10(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Variable("1"), new Variable("2"))))),
    R_11(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Variable("1"), new Variable("2"))), new Entailment(new Variable("1"), new Variable("2"))))),
    R_12(new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Variable("1"), new Variable("2")))), new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Variable("1"), new Variable("2"))), new Entailment(new Variable("1"), new Variable("2")))), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Variable("1"), new Variable("2")))))),
    R_13(new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Variable("1"), new Variable("2"))), new Entailment(new Variable("1"), new Variable("2")))), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Variable("1"), new Variable("2"))))),
    R_14(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Variable("1"), new Variable("2")))),
    R_15(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Variable("2"))))),
    R_16(new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Variable("2")))), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Variable("2"))))))),
    R_17(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Variable("2")))))),
    R_18(new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Variable("1"), new Variable("2"))), new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Variable("2"))))), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Variable("2"))))))),
    R_19(new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Variable("2"))))), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Variable("2")))))),
    R_20(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Variable("2"))))),
    R_21(new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Variable("2"))), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1"))))), new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1"))))))),
    R_22(new Entailment(new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Variable("2"))), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1"))))), new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1")))))), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Variable("2"))), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1"))))), new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1"))))))))),
    R_23(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Variable("2"))), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1"))))), new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1")))))))),
    R_24(new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Variable("2")))), new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Variable("2"))), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1"))))), new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1"))))))), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1"))))), new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1"))))))))),
    R_25(new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Variable("2"))), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1"))))), new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1"))))))), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1"))))), new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1")))))))),
    R_26(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1"))))), new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1"))))))),
    R_27(new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1")))))), new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1"))))), new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1")))))), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1")))))))),
    R_28(new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1"))))), new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1")))))), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1"))))))),
    R_29(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1")))))),
    R_30(new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2"))))),
    R_31(new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2")))), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2"))))))),
    R_32(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2")))))),
    R_33(new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2")))), new Entailment(new Not(new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2"))))))),
    R_34(new Entailment(new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2")))), new Entailment(new Not(new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2")))))), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2")))), new Entailment(new Not(new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2"))))))))),
    R_35(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2")))), new Entailment(new Not(new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2")))))))),
    R_36(new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2"))))), new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2")))), new Entailment(new Not(new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2"))))))), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2"))))))))),
    R_37(new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2")))), new Entailment(new Not(new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2"))))))), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2")))))))),
    R_38(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2"))))))),
    R_39(new Entailment(new Not(new Variable("2")), new Entailment(new Not(new Variable("2")), new Not(new Variable("2"))))),
    R_40(new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Not(new Variable("2")), new Not(new Variable("2")))), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Not(new Variable("2")), new Not(new Variable("2"))))))),
    R_41(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Not(new Variable("2")), new Not(new Variable("2")))))),
    R_42(new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Not(new Variable("2"))), new Not(new Variable("2"))))),
    R_43(new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Not(new Variable("2"))), new Not(new Variable("2")))), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Not(new Variable("2"))), new Not(new Variable("2"))))))),
    R_44(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Not(new Variable("2"))), new Not(new Variable("2")))))),
    R_45(new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Not(new Variable("2")), new Not(new Variable("2")))), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Not(new Variable("2"))), new Not(new Variable("2")))), new Entailment(new Not(new Variable("2")), new Not(new Variable("2")))))),
    R_46(new Entailment(new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Not(new Variable("2")), new Not(new Variable("2")))), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Not(new Variable("2"))), new Not(new Variable("2")))), new Entailment(new Not(new Variable("2")), new Not(new Variable("2"))))), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Not(new Variable("2")), new Not(new Variable("2")))), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Not(new Variable("2"))), new Not(new Variable("2")))), new Entailment(new Not(new Variable("2")), new Not(new Variable("2")))))))),
    R_47(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Not(new Variable("2")), new Not(new Variable("2")))), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Not(new Variable("2"))), new Not(new Variable("2")))), new Entailment(new Not(new Variable("2")), new Not(new Variable("2"))))))),
    R_48(new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Not(new Variable("2")), new Not(new Variable("2"))))), new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Not(new Variable("2")), new Not(new Variable("2")))), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Not(new Variable("2"))), new Not(new Variable("2")))), new Entailment(new Not(new Variable("2")), new Not(new Variable("2")))))), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Not(new Variable("2"))), new Not(new Variable("2")))), new Entailment(new Not(new Variable("2")), new Not(new Variable("2")))))))),
    R_49(new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Not(new Variable("2")), new Not(new Variable("2")))), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Not(new Variable("2"))), new Not(new Variable("2")))), new Entailment(new Not(new Variable("2")), new Not(new Variable("2")))))), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Not(new Variable("2"))), new Not(new Variable("2")))), new Entailment(new Not(new Variable("2")), new Not(new Variable("2"))))))),
    R_50(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Not(new Variable("2"))), new Not(new Variable("2")))), new Entailment(new Not(new Variable("2")), new Not(new Variable("2")))))),
    R_51(new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Not(new Variable("2"))), new Not(new Variable("2"))))), new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Not(new Variable("2"))), new Not(new Variable("2")))), new Entailment(new Not(new Variable("2")), new Not(new Variable("2"))))), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Not(new Variable("2")), new Not(new Variable("2"))))))),
    R_52(new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Not(new Variable("2"))), new Not(new Variable("2")))), new Entailment(new Not(new Variable("2")), new Not(new Variable("2"))))), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Not(new Variable("2")), new Not(new Variable("2")))))),
    R_53(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Not(new Variable("2")), new Not(new Variable("2"))))),
    R_54(new Entailment(new Entailment(new Not(new Variable("2")), new Not(new Variable("2"))), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2"))))), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2"))))))),
    R_55(new Entailment(new Entailment(new Entailment(new Not(new Variable("2")), new Not(new Variable("2"))), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2"))))), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2")))))), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Not(new Variable("2"))), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2"))))), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2"))))))))),
    R_56(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Not(new Variable("2"))), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2"))))), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2")))))))),
    R_57(new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Not(new Variable("2")), new Not(new Variable("2")))), new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Not(new Variable("2"))), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2"))))), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2"))))))), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2"))))), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2"))))))))),
    R_58(new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Not(new Variable("2"))), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2"))))), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2"))))))), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2"))))), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2")))))))),
    R_59(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2"))))), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2"))))))),
    R_60(new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2"))))),
    R_61(new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2")))), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2"))))))),
    R_62(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2")))))),
    R_63(new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2")))), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1")))), new Entailment(new Not(new Variable("2")), new Not(new Variable("1")))))),
    R_64(new Entailment(new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2")))), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1")))), new Entailment(new Not(new Variable("2")), new Not(new Variable("1"))))), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2")))), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1")))), new Entailment(new Not(new Variable("2")), new Not(new Variable("1")))))))),
    R_65(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2")))), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1")))), new Entailment(new Not(new Variable("2")), new Not(new Variable("1"))))))),
    R_66(new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2"))))), new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2")))), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1")))), new Entailment(new Not(new Variable("2")), new Not(new Variable("1")))))), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1")))), new Entailment(new Not(new Variable("2")), new Not(new Variable("1")))))))),
    R_67(new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2")))), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1")))), new Entailment(new Not(new Variable("2")), new Not(new Variable("1")))))), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1")))), new Entailment(new Not(new Variable("2")), new Not(new Variable("1"))))))),
    R_68(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1")))), new Entailment(new Not(new Variable("2")), new Not(new Variable("1")))))),
    R_69(new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2"))))), new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2")))), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1")))), new Entailment(new Not(new Variable("2")), new Not(new Variable("1")))))), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1")))), new Entailment(new Not(new Variable("2")), new Not(new Variable("1")))))))),
    R_70(new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Variable("1"), new Not(new Variable("2")))), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1")))), new Entailment(new Not(new Variable("2")), new Not(new Variable("1")))))), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1")))), new Entailment(new Not(new Variable("2")), new Not(new Variable("1"))))))),
    R_71(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1")))), new Entailment(new Not(new Variable("2")), new Not(new Variable("1")))))),
    R_72(new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1"))))), new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1")))), new Entailment(new Not(new Variable("2")), new Not(new Variable("1"))))), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Not(new Variable("2")), new Not(new Variable("1"))))))),
    R_73(new Entailment(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Entailment(new Not(new Variable("2")), new Entailment(new Entailment(new Variable("1"), new Not(new Variable("2"))), new Not(new Variable("1")))), new Entailment(new Not(new Variable("2")), new Not(new Variable("1"))))), new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Not(new Variable("2")), new Not(new Variable("1")))))),
    R_74(new Entailment(new Entailment(new Variable("1"), new Variable("2")), new Entailment(new Not(new Variable("2")), new Not(new Variable("1")))));
    private Expression expression;


    ContrapositionRule(Expression expression) {
        this.expression = expression;
    }

    public Expression getExpression() {
        return expression;
    }

    public static void main(String[] args) {
        for (ContrapositionRule c : ContrapositionRule.values()) {
            System.out.println(c.expression.toString());
        }
        ArrayList<Expression> result = new ArrayList<>();

        result.add(new Entailment(new Variable("a"), new Or(new Variable("a"), new Not(new Variable("a")))));
        /*
        for (ContrapositionRule s : ContrapositionRule.values()) {
            result.add(s.replace(v, new Or(v, notV)));
        }
        */
        result.add(new Entailment(new Not(new Or(new Variable("a"), new Not(new Variable("a")))), new Not(new Variable("a"))));

        result.add(new Entailment(new Not(new Variable("a")), new Or(new Variable("a"), new Not(new Variable("a")))));
        /*
        for (ContrapositionRule s : ContrapositionRule.values()) {
            result.add(s.replace(new Not(v), new Or(v, notV)));
        }
        */
        result.add(new Entailment(new Not(new Or(new Variable("a"), new Not(new Variable("a")))), new Not(new Not(new Variable("a")))));


        result.add(new Entailment(new Entailment(new Not(new Or(new Variable("a"), new Not(new Variable("a")))), new Not(new Variable("a"))), new Entailment(new Entailment(new Not(new Or(new Variable("a"), new Not(new Variable("a")))), new Not(new Not(new Variable("a")))), new Not(new Not(new Or(new Variable("a"), new Not(new Variable("a"))))))));
        result.add(new Entailment(new Entailment(new Not(new Or(new Variable("a"), new Not(new Variable("a")))), new Not(new Not(new Variable("a")))), new Not(new Not(new Or(new Variable("a"), new Not(new Variable("a")))))));
        result.add(new Not(new Not(new Or(new Variable("a"), new Not(new Variable("a"))))));
        result.add(new Entailment(new Not(new Not(new Or(new Variable("a"), new Not(new Variable("a"))))), new Or(new Variable("a"), new Not(new Variable("a")))));
        result.add(new Or(new Variable("a"), new Not(new Variable("a"))));
        for (Expression exp : result) {
            System.out.println(exp);
        }
    }
}
